### ISSUE TITLE
Sending ListPlaylistInfoCommand failed: An item with the same key has already been added

### ISSUE THREAD

**Issue by xBelladonna** [Difegue/Stylophone#16] opened 2020-12-16 01:10 UTC
First of all, thank you for identifying and fixing the issue in #14 so quickly! I've downloaded the update and it seems the problem was fixed, though there is another issue preventing the display of the playlist contents itself. I seem to be getting a couple different error messages, as below:
![image](https://user-images.githubusercontent.com/47324660/102291468-b5056b00-3f8a-11eb-8cd7-7e5996490170.png)
![image](https://user-images.githubusercontent.com/47324660/102291480-bb93e280-3f8a-11eb-80d7-a619cb196f95.png)

The queue is also blank and does not show the contents, though nothing causes a crash this time. The play/volume controls are working as expected and do play what's in the queue despite not showing it. I don't know much about Windows applications and I'm not sure how you obtained the stack trace last time but would you know how I could retrieve and supply useful debugging data from the Store app?

**Comment by Difegue** [comment] 2020-12-16 17:53
Well, you were lucky that #14 was easy to identify and that I could reproduce it 😁  
I got the stack trace from the anonymized Windows telemetry reports, but those are only sent on hard crashes.  
The store version is basically impossible to debug most of the time since it's all compiled to native code on submission, sadly.  

However, this is an error obtained while parsing results from an MPD command, so in a way it's much easier to debug! 😀  
I'm guessing from afar that this is a bug in the way I'm transforming results from the `listplaylistinfo` command into a list of tracks.  

I'd like to have the raw command output from your server so I can see what's wrong:  
You can get it using another client library, the python one seems to be the easiest to setup:  
![image](https://user-images.githubusercontent.com/8237712/102386797-de94b580-3fcf-11eb-8c55-013fcfbd81a3.png)



I should add some form of Debug view to the app so that one can see the raw MPD requests/responses as they come, but for the time being that's all I got. 😓

**Comment by Difegue** [comment] 2021-01-03 18:13
I've pushed a fix that should mitigate this problem in the next release.

**Closed by Difegue** 2021-01-03 18:13 UTC
