### ISSUE TITLE
Selecting a playlist or album in library crashes the application

### ISSUE THREAD

**Issue by xBelladonna** [Difegue/Stylophone#14] opened 2020-12-15 16:53 UTC
It seems whenever I select a playlist from the sidebar or an album from the library, the application freezes and then crashes. It's able to list the stored playlists from the server but not open them, and able to list all albums in the library but not display the tracks within. Queue is working as expected. I have tried resetting the application through Windows settings and re-installing the application. Neither of these made a difference. Do you have any advice on where to begin debugging?

**Comment by Difegue** [comment] 2020-12-15 20:29
I got a failure report from the MS Store which looks like it's linked to this issue:  
![image](https://user-images.githubusercontent.com/8237712/102268892-29ed8c00-3f1c-11eb-8410-9d89d3d98fd1.png)  

`StickyHeader` is used in both the playlist and album views, so it looks like a match - I'm not quite sure what is causing the crash here however, looks like it's the animation? 🤔

**Comment by Difegue** [comment] 2020-12-15 21:15
I can actually repro this on the 1.4 build from the MS Store - I usually only use the version I build myself for development. 😁

**Comment by Difegue** [comment] 2020-12-15 21:48
Think I found the issue - Some overzealous optimizing for the .NET Native variant.  
I didn't know much about the whole .NET Native ordeal when I added this in so I didn't think about the consequences on Store builds. 😳 I'll try to get a 1.4.1 to the Store ASAP!

**Comment by Difegue** [comment] 2020-12-16 00:05
1.4.1.0 is now live on the Store and I've verified the issue is fixed on my end.  
Thanks for notifying me!

**Closed by Difegue** 2020-12-16 00:05 UTC

**Comment by xBelladonna** [comment] 2020-12-16 01:05
Goodness me, you don't waste time! Thank you very much! There are other issues that have popped up but I believe they are different so I'll open a new issue.
