### ISSUE TITLE
Error after installation and database update

### ISSUE THREAD

**Issue by a2shiva** [Difegue/Stylophone#75] opened 2023-06-10 15:34 UTC
Hi Difegue,

Its a good app on first glance. But I ran into an error on day 1.

I bought and installed the app from the Microsoft store. I opened Stylophone and added the mpd server info. Then I clicked on Library and watched the album-arts update.

When it came to the "The Beatles (White Album)", it threw an error. I checked the files in the album and they are fine. I cleared all tags and added them back along with Album-art. I recreated the mpd database. I reinstalled Stylophone.

Each time I could replicate the same error - I have added a screenshot for your reference.

The songs are not listed when I click into the album.

But I can see the songs when I search by name and I can add them to the queue (without album-art).

Please look into it and let me know how this can be fixed.

Thanks. - Shiva

Attachments:
![1_Error](https://github.com/Difegue/Stylophone/assets/47375340/86189c51-95a9-4793-8db9-5b6e60207be4)
![2_AlbumView](https://github.com/Difegue/Stylophone/assets/47375340/57bac223-961e-49f2-a714-23af41f46720)
![3_SongSearch](https://github.com/Difegue/Stylophone/assets/47375340/da938dc5-5d8e-4206-9305-d4fd7299712e)

**Comment by Difegue** [comment] 2023-06-15 23:35
👋 Thanks for the detailed report.  
It looks like this is caused by the routine that grabs the dominant color of the album art picture. First time I'm seeing it fail in this way though!  

I've pushed a commit that should avoid the album display failing because of this - I'll have that included in the next release, in the meantime I believe the issue could be fixed on your end by simply replacing the coverart for this specific album.  

Thanks again!

**Closed** 2023-06-15 23:41 UTC

**Comment by a2shiva** [comment] 2023-06-17 13:28
Thanks Difegue.
 Feedback: I solved the problem independently using a different album art.
The cause of the error - the software fails for the "Beatles White Album". The album is almost completely white with some very tiny text in black.

Hope this helps. Cheers. - Shiva
On Fri, June, 16, 2023 5:11:17 AM, Difegue ***@***.***> wrote:
Closed #75 [https://github.com/Difegue/Stylophone/issues/75] as completed.
